### ISSUE TITLE
Delete unnecessary files

### ISSUE THREAD

**Issue by dimztimz** [flathub/org.nuspell.Nuspell#3]
The Flatpak's package contains all of the Boost headers and also Nuspell headers. Those should be deleted before shipping because they add additional 100 MB.

Here is example https://github.com/flathub/shared-modules/blob/ca1664c5d1d94899432f364f006c582898afbae2/SDL/SDL-1.2.15.json#L5-L13

**Comment by PanderMusubi** [comment]
Fixed in https://github.com/flathub/org.nuspell.Nuspell/commit/3f641282490604f152717ea52f361113b4b87b54
