### ISSUE TITLE
Update version in metainfo, delete finish-args

### ISSUE THREAD

**Issue by dimztimz** [flathub/org.nuspell.Nuspell#5]
This should get updated:

https://github.com/flathub/org.nuspell.Nuspell/blob/e4dd8cabe0e74a5d5fbc73ca2184713aececb749/org.nuspell.Nuspell.metainfo.xml#L62-L67

The following lines:

https://github.com/flathub/org.nuspell.Nuspell/blob/e4dd8cabe0e74a5d5fbc73ca2184713aececb749/org.nuspell.Nuspell.json#L14-L16

are not needed because of two reasons. Firstly, you can not access anything of host's `/usr` because that is the point of the sandbox, and secondly there is no need to because the platform extension already provides dictionaries. The program sees those as `/usr/share/hunspell`, there is no need to set DICPATH.

https://github.com/flathub/org.nuspell.Nuspell/blob/e4dd8cabe0e74a5d5fbc73ca2184713aececb749/org.nuspell.Nuspell.json#L9-L11

**Comment by PanderMusubi** [comment]
Accessing the host /usr dicts worked in my tests with `flatpak-builder --run` but perhaps that is another situation. Removed the finish args from the json and updated the xml.
